# Generated by Django 4.2.3 on 2023-08-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completed_profile',
            field=models.BooleanField(default=False),
        ),
    ]
