# Generated by Django 4.2.3 on 2023-08-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_competition_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
