# Generated by Django 4.2.3 on 2023-08-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
